# ========================================================================
# НАСТРОЙКИ КОНТРОЛЯ СООТВЕТСТВИЯ ТРЕБОВАНИЯМ БЕЗОПАСНОСТИ (РД АС / РД СВТ)
# ========================================================================
# Вы можете редактировать значения параметров для каждого класса защищенности.
# Скрипт "security_checker.ps1" считывает этот файл при комплаенс-контроле.

[3Б]
# Минимальная длина пароля
req_len=6
# Требование к истории повторения паролей (кол-во сохраненных)
req_hist=0
# Максимальный срок действия пароля в днях
req_max_days=180
# Число попыток входа до блокировки
req_deny=5
# Время блокировки аккаунта в секундах
req_unlock_time=300
# Таймаут неактивности сессии в секундах (заставка / inactivity limit)
req_tmout=1800
# Безопасное удаление файлов (Dallas Lock / SNS / SDelete)
req_secdel=optional
# Очистка Swap/Pagefile при выключении (ClearPageFileAtShutdown)
req_swap=optional
# Блокировка консоли при простое
req_console=optional
# Защита процессов LSA (RunAsPPL)
req_ptrace=optional
# Ограничение запуска скриптов (PowerShell Execution Policy)
req_interpreters=optional
# Режим аудита событий безопасности
req_audit=optional

[2Б]
req_len=6
req_hist=0
req_max_days=180
req_deny=5
req_unlock_time=300
req_tmout=1800
req_secdel=optional
req_swap=Включен
req_console=optional
req_ptrace=optional
req_interpreters=optional
req_audit=Включен

[1Д]
req_len=6
req_hist=0
req_max_days=180
req_deny=5
req_unlock_time=300
req_tmout=1800
req_secdel=optional
req_swap=Включен
req_console=optional
req_ptrace=optional
req_interpreters=optional
req_audit=Включен

[1Г]
req_len=6
req_hist=0
req_max_days=180
req_deny=5
req_unlock_time=300
req_tmout=1800
req_secdel=optional
req_swap=Включен
req_console=optional
req_ptrace=optional
req_interpreters=optional
req_audit=Включен

[3А]
req_len=6
req_hist=1
req_max_days=90
req_deny=5
req_unlock_time=900
req_tmout=600
req_secdel=optional
req_swap=Включен
req_console=Включен
req_ptrace=Включен
req_interpreters=optional
req_audit=Включен

[2А]
req_len=6
req_hist=1
req_max_days=90
req_deny=5
req_unlock_time=900
req_tmout=600
req_secdel=optional
req_swap=Включен
req_console=Включен
req_ptrace=Включен
req_interpreters=optional
req_audit=Включен

[1В]
req_len=6
req_hist=1
req_max_days=90
req_deny=5
req_unlock_time=900
req_tmout=600
req_secdel=optional
req_swap=Включен
req_console=Включен
req_ptrace=Включен
req_interpreters=optional
req_audit=Включен

[1Б]
req_len=8
req_hist=1
req_max_days=60
req_deny=3
req_unlock_time=1800
req_tmout=300
req_secdel=Включен
req_swap=Включен
req_console=Включен
req_ptrace=Включен
req_interpreters=optional
req_audit=Включен

[1А]
req_len=8
req_hist=1
req_max_days=30
req_deny=3
req_unlock_time=3600
req_tmout=300
req_secdel=Включен
req_swap=Включен
req_console=Включен
req_ptrace=Включен
req_interpreters=Включен
req_audit=Включен (строгие правила)
